### ISSUE TITLE
hipGetDeviceCount is incorrectly mapped to cuGetDeviceCount

### ISSUE THREAD

**Issue by jussienko** [cschpc/hop#1]
hipGetDeviceCount should be mapped to corresponding runtime API call , i.e. cudaGetDeviceCount instead of the  driver API version cuGetDeviceCount.

**Comment by mlouhivu** [comment]
Thanks for reporting this! Affected also other HIP identifiers that have two or more CUDA counterparts. Should be fixed now and included in 0.4.
